// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbE2_5HoSqMH-n39nvTrgPZ_CTv-Croec',
    appId: '1:136604765510:web:264b774dcbf20101b92947',
    messagingSenderId: '136604765510',
    projectId: 'fir-sample-4dbd3',
    authDomain: 'fir-sample-4dbd3.firebaseapp.com',
    storageBucket: 'fir-sample-4dbd3.appspot.com',
    measurementId: 'G-KR53Z0PT8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_MiL3GEim3GFy5DtoCXTvlhGzTMipxI',
    appId: '1:136604765510:android:70539322d3d013ddb92947',
    messagingSenderId: '136604765510',
    projectId: 'fir-sample-4dbd3',
    storageBucket: 'fir-sample-4dbd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIZJsfuseOYRsHcG8rzPZ9S6EQHaGX9E',
    appId: '1:136604765510:ios:3211d4b10d0b2c3eb92947',
    messagingSenderId: '136604765510',
    projectId: 'fir-sample-4dbd3',
    storageBucket: 'fir-sample-4dbd3.appspot.com',
    iosClientId: '136604765510-oh1e99ejjirecqg9evp2k69lv837vs1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqIZJsfuseOYRsHcG8rzPZ9S6EQHaGX9E',
    appId: '1:136604765510:ios:3211d4b10d0b2c3eb92947',
    messagingSenderId: '136604765510',
    projectId: 'fir-sample-4dbd3',
    storageBucket: 'fir-sample-4dbd3.appspot.com',
    iosClientId: '136604765510-oh1e99ejjirecqg9evp2k69lv837vs1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
